// Project-local MCP Blueprint graph pin wrapper.

#include "BlueprintEditorBridge/McpBlueprintGraphPin.h"

#include "BlueprintEditorLibrary.h"
#include "EdGraphSchema_K2.h"
#include "K2Node.h"
#include "Logging/StructuredLog.h"

bool FMcpBlueprintGraphPin::operator==(const FMcpBlueprintGraphPin&) const = default;
bool FMcpBlueprintGraphPin::operator!=(const FMcpBlueprintGraphPin&) const = default;

FMcpBlueprintGraphPin UMcpBlueprintGraphPinLibrary::FromNativePin(UEdGraphPin* Pin)
{
	if(!Pin)
	{
		return FMcpBlueprintGraphPin{};
	}

	UK2Node* OwningNode = Cast<UK2Node>(Pin->GetOwningNode());
	if(!OwningNode)
	{
		return FMcpBlueprintGraphPin{};
	}

	FMcpBlueprintGraphPin ScriptPin;
	ScriptPin.Node = OwningNode;
	ScriptPin.PinDirection = Pin->Direction;
	ScriptPin.PinName = Pin->PinName;

	int32 LogicalIndex = 0;
	for(UEdGraphPin* NodePin : OwningNode->Pins)
	{
		if(NodePin->bHidden)
		{
			continue;
		}
		if(NodePin->Direction == Pin->Direction)
		{
			if(NodePin == Pin)
			{
				ScriptPin.PinIndex = LogicalIndex;
				break;
			}
			LogicalIndex++;
		}
	}

	return ScriptPin;
}

bool UMcpBlueprintGraphPinLibrary::IsValid(const FMcpBlueprintGraphPin& Pin)
{
	if( Pin == FMcpBlueprintGraphPin() )
	{
		return false;
	}

	return true;
}

bool UMcpBlueprintGraphPinLibrary::IsSameNativePin(const FMcpBlueprintGraphPin& Pin, const FMcpBlueprintGraphPin& Other)
{
	const UEdGraphPin* NativePin = GetNativePinSafe(Pin);
	const UEdGraphPin* OtherNativePin = GetNativePinSafe(Other);
	if(!NativePin || !OtherNativePin)
	{
		return false;
	}

	return NativePin == OtherNativePin;
}

bool UMcpBlueprintGraphPinLibrary::SetPinValue(const FMcpBlueprintGraphPin& Pin, const FString& Value)
{
	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();
	if(UEdGraphPin* NativePin = GetNativePinSafe(Pin))
	{
		Schema->TrySetDefaultValue(*NativePin, Value, false);
		// Reset default values
		if (!Schema->IsPinDefaultValid(NativePin, NativePin->DefaultValue, NativePin->DefaultObject, NativePin->DefaultTextValue).IsEmpty())
		{
			Schema->ResetPinToAutogeneratedDefaultValue(NativePin, false);
			UE_LOGFMT(LogBlueprint, Warning, "Failed to set default value {Value} on {PinName}", Value, NativePin->PinName);
			return false;
		}
		return true;
	}
	return false;
}

bool UMcpBlueprintGraphPinLibrary::TryCreateConnection(const FMcpBlueprintGraphPin& Pin, const FMcpBlueprintGraphPin& Other)
{
	UEdGraphPin* SelfNativePin = GetNativePinSafe(Pin);
	UEdGraphPin* OtherNativePin = GetNativePinSafe(Other);
	if(!SelfNativePin || !OtherNativePin)
	{
		return false;
	}

	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();
	return Schema->TryCreateConnection(SelfNativePin, OtherNativePin);
}

bool UMcpBlueprintGraphPinLibrary::CanCreateConnection(const FMcpBlueprintGraphPin& Pin, const FMcpBlueprintGraphPin& Other)
{
	const UEdGraphPin* NativePin = GetNativePinSafe(Pin);
	const UEdGraphPin* OtherNativePin = GetNativePinSafe(Other);
	if(!NativePin || !OtherNativePin)
	{
		return false;
	}

	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();
	return Schema->CanCreateConnection(NativePin, OtherNativePin).Response != CONNECT_RESPONSE_DISALLOW;
}

bool UMcpBlueprintGraphPinLibrary::BreakPinLinks(const FMcpBlueprintGraphPin& Pin)
{
	UEdGraphPin* NativePin = GetNativePinSafe(Pin);
	if(!NativePin)
	{
		return false;
	}

	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();
	Schema->BreakPinLinks(*NativePin, true);
	return true;
}

bool UMcpBlueprintGraphPinLibrary::BreakSinglePinLink(const FMcpBlueprintGraphPin& Pin, const FMcpBlueprintGraphPin& Other)
{
	UEdGraphPin* SelfNativePin = GetNativePinSafe(Pin);
	UEdGraphPin* OtherNativePin = GetNativePinSafe(Other);
	if(!SelfNativePin || !OtherNativePin)
	{
		return false;
	}

	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();
	Schema->BreakSinglePinLink(SelfNativePin, OtherNativePin);
	return true;
}

FName UMcpBlueprintGraphPinLibrary::GetPinName(const FMcpBlueprintGraphPin& Pin)
{
	UEdGraphPin* NativePin = GetNativePinSafe(Pin);
	if(!NativePin)
	{
		return NAME_None;
	}

	return NativePin->PinName;
}

TEnumAsByte<EEdGraphPinDirection> UMcpBlueprintGraphPinLibrary::GetPinDirection(const FMcpBlueprintGraphPin& Pin)
{
	return Pin.PinDirection;
}

FString UMcpBlueprintGraphPinLibrary::GetPinTypeAsJsonSchema(const FMcpBlueprintGraphPin& Pin)
{
	UEdGraphPin* NativePin = GetNativePinSafe(Pin);
	if(!NativePin)
	{
		return TEXT("");
	}

	UK2Node* OwningNode = Cast<UK2Node>(NativePin->GetOwningNode());
	if(!OwningNode)
	{
		return TEXT("");
	}

	const FEdGraphPinType& PinType = NativePin->PinType;
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Exec)
	{
		return TEXT("{\"type\":\"exec\"}");
	}

	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Boolean)
	{
		return TEXT("{\"type\":\"boolean\"}");
	}

	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Int || PinType.PinCategory == UEdGraphSchema_K2::PC_Int64)
	{
		return TEXT("{\"type\":\"integer\"}");
	}

	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Real || PinType.PinCategory == UEdGraphSchema_K2::PC_Float || PinType.PinCategory == UEdGraphSchema_K2::PC_Double)
	{
		return TEXT("{\"type\":\"number\"}");
	}

	if (PinType.PinCategory == UEdGraphSchema_K2::PC_String || PinType.PinCategory == UEdGraphSchema_K2::PC_Text || PinType.PinCategory == UEdGraphSchema_K2::PC_Name)
	{
		return TEXT("{\"type\":\"string\"}");
	}

	return FString::Printf(TEXT("{\"type\":\"object\",\"pinCategory\":\"%s\"}"), *PinType.PinCategory.ToString());
}

FText UMcpBlueprintGraphPinLibrary::GetPinTypeDisplayString(const FMcpBlueprintGraphPin& Pin)
{
	UEdGraphPin* NativePin = GetNativePinSafe(Pin);
	if(!NativePin)
	{
		return FText();
	}

	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();
	return Schema->TypeToText(NativePin->PinType);
}

FEdGraphPinType UMcpBlueprintGraphPinLibrary::GetPinType(const FMcpBlueprintGraphPin& Pin)
{
	UEdGraphPin* NativePin = GetNativePinSafe(Pin);
	if(!NativePin)
	{
		return FEdGraphPinType();
	}

	return NativePin->PinType;
}

FString UMcpBlueprintGraphPinLibrary::GetPinValue(const FMcpBlueprintGraphPin& Pin)
{
	UEdGraphPin* NativePin = GetNativePinSafe(Pin);
	if(!NativePin)
	{
		return TEXT("");
	}

	return NativePin->GetDefaultAsString();
}

UK2Node* UMcpBlueprintGraphPinLibrary::GetOwningNode(const FMcpBlueprintGraphPin& Pin)
{
	return Pin.Node;
}

TArray<FMcpBlueprintGraphPin> UMcpBlueprintGraphPinLibrary::ListConnectedPins(const FMcpBlueprintGraphPin& Pin)
{
	TArray<FMcpBlueprintGraphPin> Result;
	UEdGraphPin* NativePin = GetNativePinSafe(Pin);
	if(!NativePin)
	{
		return Result;
	}

	for(UEdGraphPin* LinkedToPin : NativePin->LinkedTo)
	{
		FMcpBlueprintGraphPin WrappedPin = FromNativePin(LinkedToPin);
		if(::IsValid(WrappedPin.Node))
		{
			Result.Add(WrappedPin);
		}
	}
	return Result;
}

UEdGraphPin* UMcpBlueprintGraphPinLibrary::GetNativePinSafe(const FMcpBlueprintGraphPin& Pin)
{
	if(!::IsValid(Pin.Node))
	{
		return nullptr;
	}

	// Collect visible pins in the requested direction so we can index into them
	// and perform an outward search if needed.
	TArray<UEdGraphPin*, TInlineAllocator<16>> DirectionalPins;
	for(UEdGraphPin* NativePin : Pin.Node->Pins)
	{
		if(!NativePin->bHidden && NativePin->Direction == Pin.PinDirection)
		{
			DirectionalPins.Add(NativePin);
		}
	}

	// Fast path: index and name both match
	if(DirectionalPins.IsValidIndex(Pin.PinIndex) && DirectionalPins[Pin.PinIndex]->PinName == Pin.PinName)
	{
		return DirectionalPins[Pin.PinIndex];
	}

	// The pin at the expected index has a different name — the graph has been
	// modified and indices have drifted. Search outward from PinIndex to find
	// the nearest pin that still has the correct name.
	for(int32 Distance = 1; Distance < DirectionalPins.Num(); ++Distance)
	{
		const int32 Forward = Pin.PinIndex + Distance;
		if(DirectionalPins.IsValidIndex(Forward) && DirectionalPins[Forward]->PinName == Pin.PinName)
		{
			return DirectionalPins[Forward];
		}

		const int32 Backward = Pin.PinIndex - Distance;
		if(DirectionalPins.IsValidIndex(Backward) && DirectionalPins[Backward]->PinName == Pin.PinName)
		{
			return DirectionalPins[Backward];
		}
	}

	return nullptr;
}
